CREATE DATABASE invoice;
CREATE USER test WITH PASSWORD '123456';
GRANT CONNECT ON DATABASE invoice TO test;

\c invoice postgres
GRANT USAGE, CREATE ON SCHEMA public TO test;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO test;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO test;